### ISSUE TITLE
Can you provide a sample input data?

### ISSUE THREAD

**Issue by crossdawn** [curtis992250/FOPPRplot#1]
thank you very much

**Comment by TaroballzChen** [comment]
Sorry!! This program has to be used with anthoer program which developed by LabVIEW. the input data was updated continuously, the format of data as follow:
```
...
...
2.000000        0.910051
3.000000.       0.910062
4.000000.       0.910061
5.000000.       0.910053
6.000000.       0.910060
...
...
```
I'll update the method how to use
